### PR TITLE
Closes #55

### LINKED ISSUE #55: Add support for encrypted maven credentials
In many situations, when working with private repositories, there is a need to use encrypted maven credentials. Such setup requires having the file `settings-security.xml` additional to `settings.xml` in `~/.m2`. Hence, I propose to modify the maven binding to include both files.

The implementation would be quite simple since the security settings can be passed to Maven with the system property `settings.security`. For instance:

```
mvn -s ~/.credentials/settings.xml -Dsettings.security=~/.credentials/settings-security.xml package
```

### PR DESCRIPTION
**Pull request by Smasherr**
## Summary
Add support for encrypted maven credentials.

## Use Case
Usage of encrypted maven credentials (`settings.xml` plus `settings-security.xml`).

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Review by dmikusa-pivotal — CHANGES_REQUESTED** [review]
I didn't try running yet, but one request based on a quick read-through of the changes. It looks like you modified the existing test case to check for both files. Would you be able to make two separate test cases?

I'd prefer if the existing test case remains the same & an additional test case is added validating the new scenario. That way we're validating both cases, i.e. where a.) just a settings.xml is provided and b.) both settings.xml and settings-security.xml are provided.

**Review by dmikusa-pivotal — APPROVED** [review]
Looks great. Unit tests pass for me. Changed a few things and they broke as expected. Tested some builds with and without a security file. All worked as expected. Thanks for the PR!

**Comment by dmikusa-pivotal** [comment]
Github is giving me issues merging. As soon as these clear up, I will merge this. Sorry for the delay.

**Comment by Smasherr** [comment]
> Github is giving me issues merging. As soon as these clear up, I will merge this. Sorry for the delay.

No worries, thank you for your quick operation!

**Comment by Smasherr** [comment]
Just one more question: what's your release cycle?

**Comment by dmikusa-pivotal** [comment]
We don't have a time-based release cycle, it's more or less when there's something to release, we'll cut a new release. We are trying to iterate fast and get new features out quickly. 

I'll release this one today. It'll take a little time to get picked up by the paketo-buildpacks/java buildpack & the builder (maybe a day or two). You can use it directly in the meantime with `pack build -b`.

Hope that helps!

**Pull request merged**
