### PR TITLE
Distribute binaries

### LINKED ISSUE #159: Support distribution of binaries
We have need for `mvn` or `mvnd` to be distributed on a build layer.  This makes a maven binary available for subsequent buildpacks to use.  In this scenario, the source project does not necessarily contain a `pom.xml`.

## Describe the Enhancement

The enhancement allows the maven buildpack to operate as a [distribution buildpack](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md#stack-choice).  Subsequent buildpacks can use the maven binary to perform maven operations.

## Possible Solution

The maven buildpack could succeed to detect if `BP_MAVEN_COMMAND` is set to either `mvn` or `mvnd`.  During the build phase, if `BP_MAVEN_COMMAND` is set to either `mvn` or `mvnd` then the corresponding binary is contributed as a build layer.

A buildpack that requires the maven buildpack might be expected to explicitly set a flag to disable running the maven command.  The default operation of the buildpack, in the absence of the flag, would continue to run the build command.

```go
Requires: []libcnb.BuildPlanRequire{
	{
		Name: maven.PlanEntryMaven,
		Metadata: map[string]interface{}{
			"RunBuild": false,
		},
	},
}
```

The current cache layer on which `mvn`/`mvd` are distributed would be made available as a build and cache layer.

## Motivation

Our motivation is to support injection of Jars into an application image in a non-JVM source project.  For example, python is a common language for data science projects and data science projects in python often use PySpark for distributed computation.  Such use-cases commonly need to install a single Jar file, or a small number of Jar files, and make them available in the CLASSPATH.  The set of Jars to install depend on the dependencies used in the Python project.   Application developers do not want to manage both a python build system and a maven/gradle/sbt build system.  Supporting a "distribution only" operation in the maven buildpack allows us to provide a subsequent buildpack to detect a PySpark project and inject appropriate Jar files.

Given this motivation, a data-science oriented build image might set `BP_MAVEN_COMMAND=mvn` by default.  The buildpack that contributes the Jars would depend on the maven buildpack and set `RunBuild: false`.  This moves the problem of managing dependencies in a `pom.xml` from the data-scientist to the platform operator.

### PR DESCRIPTION
**Pull request by AidanDelaney**
Support distribution of binaries in maven buildpack

closes #159 

## Summary

If no `pom.xml` is available the buildpack now provides "maven`

Adds a `Command` build plan metadata entry to request that a specific maven binary is distributed.  A `RunBuild` build plan metadata entry allows subsequent buildpacks to omit project build stages.  The changes allow the maven buildpack to be used in a "distribute only" mode.

## Use Cases

Under discussion in #159 

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by dmikusa** [comment]
>Adds a Command build plan metadata entry to request that a specific maven binary is distributed. A RunBuild build plan metadata entry allows subsequent buildpacks to omit project build stages. The changes allow the maven buildpack to be used in a "distribute only" mode.

I'm not sure I understand the need for the metadata entries. Can you expand on the high level design and your requirements?

1. There is a buildplan entry for Maven (the binary). The buildpack provides and requires that if the `pom.xml` file exists. That seems reasonable to me.
2. There is a buildplan entry for PlanEntryJVMApplicationPackage. Presently, this doesn't matter because detect won't pass unless something else requires it and so the buildpack itself doesn't need to check for this. However, if we're going to expand the buildpack to run and only provide binaries, then we'll need to check for the presence of this buildplan entry. If it's present, that can be a trigger for the build phase. An example is executable-jar, it will require PlanEntryJVMApplicationPackage if it needs source code to be compiled into a JAR. If it doesn't, because it already has a JAR file then this entry isn't added and Maven won't run.

If it helps we can try to graph out the buildplan entries and provide some example flows. This is probably the most complicated part of the Java buildpack buildplan, because it covers both source and pre-compiled asset builds. We have to be very careful making changes with this logic.

**Comment by AidanDelaney** [comment]
At a high-level I want a buildpack to provide `mvn` or `mvnd` to subsequent buildpacks at build time.  In addition, I do not want to run a build as the source project requiring maven may not be a JVM project.  Subsequent buildpacks may then use `mvn` to perform operations.  The concrete requirement in https://github.com/paketo-buildpacks/maven/issues/159 is to use the maven-copy-dependencies plugin to copy dependencies.

I introduced a `Command` into the  build plan metadata to allow a buildpack to request the maven buildpack to make either `mvn` or `mvnd` available as a build layer.  The `RunBuild` build plan metadata allows subsequent buildpacks to disable running of the build logic.

Taking the README.md as a description of the logic, then I'm extending the logic as follows:

The buildpack will do the following:

* Requests that a JDK be installed
* Links the `~/.m2` to a layer for caching
* If `mvn` or `mvnd` are requested for distribution then provide a build layer containing `mvn` or `mvnd`
* if a source build is requested then 
  * If `<APPLICATION_ROOT>/mvnw` exists
    * Runs `<APPLICATION_ROOT>/mvnw -Dmaven.test.skip=true --no-transfer-progress package` to build the application
  * If `<APPLICATION_ROOT>/mvnw` does not exist
    * Contributes Maven to a layer with all commands on `$PATH`
    * Runs `<MAVEN_ROOT>/bin/mvn -Dmaven.test.skip=true --no-transfer-progress package` to build the application
    * Caches `$BP_MAVEN_BUILT_ARTIFACT` to a layer
  * Removes the source code in `<APPLICATION_ROOT>`
  * If `$BP_MAVEN_BUILT_ARTIFACT` matched a single file
    * Restores `$BP_MAVEN_BUILT_ARTIFACT` from the layer, expands the single file to `<APPLICATION_ROOT>`
  * If `$BP_MAVEN_BUILT_ARTIFACT` matched a directory or multiple files
    * Restores the files matched by `$BP_MAVEN_BUILT_ARTIFACT` to `<APPLICATION_ROOT>`
 
I can see that the resolution of `RunBuild` in the current PR is incorrect.  It should only be set to `false` only if there is a single build plan entry that requests `RunBuild: false`.  Where other build plan entries exist for `maven` or `jvm-application-package` then `RunBuild` should be resolved to `true`.

Hopefully I've provided more clarity around the intention of providing a _distribution_ of `mvn` or `mvnd`.  The core idea is that there are situations where `mvn` is required, but a source build using `mvn` is not required.

**Comment by dmikusa** [comment]
Sorry for the delay on this. It is on my radar, I'm just trying to make some time to dig into it more. Thanks

**Comment by dmikusa** [comment]
I have been looking at this and working on some code changes for a few different scenarios.

I'd rather avoid having the command and runbuild metadata if we can help it. I think we can meet your requirements and not require that, but I'm still in the progress of testing build plans.

This is taking a little longer as I think it's necessitating some code clean up as well. The logic about picking which maven to use needs to be abstracted out.

Lastly, it is a little ambitious but Id like to add in support for the opposite case as well, ie just build with no install of Maven.

**Comment by AidanDelaney** [comment]
Closing as #185 is a cleaner approach.

**Pull request closed without merging**
